import deployments from "./deployments.json";

import { isAvailable, LOCAL_CHAIN_ID } from "./chains";

/**
 * Every address the app needs, per chain.
 *
 * Generated by `scripts/app-deployments.py` from the contracts' own ledgers and
 * `Addresses.sol`, and imported rather than fetched. A chain with no complete
 * ledger simply has no entry, and {addressesFor} answers with zeros — every
 * read then returns nothing and the app draws its empty state, which is the
 * honest failure for a chain nothing was deployed to.
 */
const ZERO = "0x0000000000000000000000000000000000000000" as const;

export type Addresses = {
  namespaceFactory: `0x${string}`;
  namespaceResolver: `0x${string}`;
  slotFactory: `0x${string}`;
  ensVerifiableFactory: `0x${string}`;
  ensUserRegistryImpl: `0x${string}`;
  ensEthRegistry: `0x${string}`;
  ensEthRegistrar: `0x${string}`;
  ensUniversalResolver: `0x${string}`;
  mockUsdc: `0x${string}`;
  minimumTenureHook: `0x${string}`;
};

const EMPTY: Addresses = {
  namespaceFactory: ZERO,
  namespaceResolver: ZERO,
  slotFactory: ZERO,
  ensVerifiableFactory: ZERO,
  ensUserRegistryImpl: ZERO,
  ensEthRegistry: ZERO,
  ensEthRegistrar: ZERO,
  ensUniversalResolver: ZERO,
  mockUsdc: ZERO,
  minimumTenureHook: ZERO,
};

const { shared, chains } = deployments as {
  shared: Partial<Addresses>;
  chains: Record<string, Partial<Addresses> | undefined>;
};

/**
 * The address book for a chain.
 *
 * Falls back to the local fork when the chain is unknown — which is what a
 * disconnected wallet reports, and the fork is where somebody with no wallet
 * connected is almost certainly looking.
 */
export function addressesFor(chainId?: number): Addresses {
  const entry = chains[String(chainId ?? LOCAL_CHAIN_ID)];
  // `shared` regardless: the ENS and 0xSlots contracts are the same deployment
  // on both chains, so they are known even where this protocol is not.
  return { ...EMPTY, ...shared, ...(entry ?? {}) };
}

export const isDeployedOn = (chainId?: number) =>
  addressesFor(chainId).namespaceFactory !== ZERO;

/**
 * Which chains this build can offer: deployed, and compiled in.
 *
 * Typed as wagmi's own chain-id union rather than `number[]`, so
 * `switchChain({ chainId })` accepts an entry straight out of this list. The
 * cast is safe by construction: the keys come from the generated address book,
 * whose chains are the ones in {CHAINS}.
 */
export const DEPLOYED_CHAIN_IDS = Object.keys(chains)
  .map(Number)
  .filter((id) => isDeployedOn(id) && isAvailable(id)) as (
  | typeof LOCAL_CHAIN_ID
  | 11155111
)[];

/** Every role and its admin — what a registry's own deployer takes. */
export const ALL_ROLES =
  0x1111111111111111111111111111111111111111111111111111111111111111n;

/** What a namespace needs on its registry, and nothing more. */
export const ROLE_REGISTRAR = 1n << 0n;
export const ROLE_UNREGISTER = 1n << 12n;

/** `SlotNamespace.LabelKind`, as the contract numbers it. */
export const KIND_COMMON = 0;
export const KIND_SPONSORING = 1;
